name: GitHub Page

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  github-page:
    name: GitHub Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.1.0'
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
      - name: Unit Test
        run: yarn workspace @world/web test -u
      - name: Build Production
        run: yarn workspace @world/web build
      - name: Add .nojekyll file
        run: touch services/web/out/.nojekyll
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: services/web/out
          clean: true
